CREATE SCHEMA IF NOT EXISTS G3_GESTOR_VENTAS;
USE G3_GESTOR_VENTAS;

-- Faltan rellenar pero seran rellenados en la aplicación
SELECT * FROM USUARIOS;
SELECT * FROM AVATARUSUARIO;
SELECT * FROM VENTAS;
SELECT * FROM DETALLE_VENTAS;
SELECT * FROM PAGOS;

-- Rellenados con datos de prueba
SELECT * FROM CATEGORIAS;
SELECT * FROM CLIENTES;
SELECT * FROM METODO_PAGO;
SELECT * FROM PRODUCTOS;
SELECT * FROM PROVEEDORES;
SELECT * FROM TIPOCLIENTE;
SELECT * FROM TIPOUSUARIO;

